### PR TITLE
Fix some installation issues

### PR DESCRIPTION
**Pull request by kochd**
I encountered some issues while using this script:

- It seams like php copy() does not handle http(s)_proxy environment variables correctly. I was not able to establish a connection with php while curl/wget/whatever worked fine.
- Solution: Replace the php copy() call with wget as wget was used before

- Replaced the sha384 checksumming using php by just making use of sha384sum

After those changes the script run without any errors.

### CODE REVIEW

**Comment by kochd** [comment]
That patch is provided under the terms and the conditions of the AGPL-3.0 as used by this repository. If you need a CLA on top of that you're probably using the wrong license.

**Comment by stripthis** [comment]
@kochd the CLA is based on the harmony template. It covers us in case for example in the future we want to change the license from AGPL to another OSI compliant free software license. See. http://www.harmonyagreements.org/overview.html

**Comment by dlen** [comment]
@kochd thanks for your contrib and sorry for the delay I will try to review it in the following days!

**Comment by stripthis** [comment]
@dlen @kochd If all reviewers as well as the original author agree that the submission is trivial, the commit text should include "CLA: trivial."

**Pull request closed without merging**
